name: 4p3
url: http://4p3.github.io
description: "Omlengesek elvont dolgokrol, a vilagrol, meg minden szarrol."
author: 4p3
markdown: redcarpet
paginate: 7
paginate_path: "oldal:num"
exclude: [vendor]
gems:
  - jekyll-sitemap